server:
  port: 8081
spring:
  thymeleaf:
    cache: false

  #\u914D\u7F6E\u6570\u636E\u5E93
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tsc
    password: tsc123
    url: jdbc:mysql:假装有点保密意识/test?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=UTC
    #\u90AE\u7BB1\u914D\u7F6E
  mail:
    host: smtp.qq.com
    port: 587
    username: 2465668576@qq.com
    password: mgjlurmdqgfieaig
    from: 2465668576@qq.com
    properties:
      mail:
        debug: true
      stmp:
        auth: true
        ssl:
          enable: true

#\u914D\u7F6Esql\u6620\u5C04
mybatis:
  type-aliases-package: com.service
  mapper-locations:
    - mapper/*
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#
project:
  project1:
    environment:
      - 准生产
      - 测试主
      - 测试次
    name: 知轮
    id: 1
    describe: 假装有点保密意识
    device:
      - device1:
        id: 1
        name: 管理后台
        loginPage: web
        loginType: 1
        loginParam: {username: username,password: 假装有点保密意识,grant_type: password}
        smsParam: {}
        smsUri:
        smsLoginParam: {}
        loginUri: /oauth/token
        tokenPath: $.access_token
        loginRely:
          userId: $.userId
          token: $.access_token
        deviceTypeList:
          - 唐胖的管理后台账号
        environment:
          - loginHost: 假装有点保密意识
            loginHeader: {Authorization: Basic 假装有点保密意识==}
            smsHeader: {}
            account:
              - - tsc
                - tscpear
              - - 1358809666
            host: 假装有点保密意识

          - loginHost: 假装有点保密意识
            loginHeader: {Authorization: Basic 假装有点保密意识==}
            smsHeader: {}
            account:
              - - tsc
                - tsccs
              - - 1358809666
            host: 假装有点保密意识


          - loginHost: 假装有点保密意识
            loginHeader: {Authorization: Basic 假装有点保密意识== }
            smsHeader: {}
            account:
              - - tsc
                - tscpear
              - - 1358809666
            host: 假装有点保密意识



      - device2:
        id: 2
        name: 知轮商家
        loginPage: 假装有点保密意识
        loginType: 1
        smsParam: {deviceId: "假装有点保密意识",mobile: "username"}
        loginParam:
          application: app_zhilun
          deviceId: 假装有点保密意识
          grant_type: store_password
          mobile: username
          password: 假装有点保密意识
        smsLoginParam: {smsCode: 假装有点保密意识,deviceId: 假装有点保密意识,mobile: username,version: 3.0.0,grant_type: sms_code}
        smsUri: /sms/code
        loginUri: /oauth/token
        tokenPath: $.access_token
        loginRely:
          token: $.access_token
          userId: $.userId
          userType: $.userType
          scope: $.scope
        deviceTypeList:
          - 网红门店账号
          - 网红门店下服务车账号
          - 普通门店账号
          - 普通社会服务车账号
          - 取货点
          - 取货方门店账号
          - 取货方门店下服务车账号
          - 取货方社会服务车账号
        environment:
#          准生产
          - loginHost: 假装有点保密意识
            loginHeader: {Authorization: Basic 假装有点保密意识}
            smsHeader: {}
            account:
              - - 13588096710
                - 18329133828
              - - 12900000205
              - - 14400000005
              - - 13200000002
            host: 假装有点保密意识
#            测试主
          - loginHost: 假装有点保密意识
            loginHeader: {Authorization: Basic 假装有点保密意识}
            smsHeader: {}
            account:
              - - 13588096710
                - 12900000205
              - - 12900000205
              - - 13200000000
              - - 13200000004
            host: 假装有点保密意识
#            测试次
          - loginHost: 假装有点保密意识
            loginHeader: {Authorization: Basic 假装有点保密意识}
            smsHeader: {}
            account:
              - - 13588096710
                - 186571905346
              - - 1358809666
              - - 13200000000
              - - 13200000004
            host: 假装有点保密意识
      - device3:
        id: 3
        name: 知轮三包
        loginPage: 假装有点保密意识
        loginType: 1
        smsParam: {deviceId: "719910247738029",mobile: "username"}
        loginParam:
          grant_type: password
          username: username
          password: 假装有点保密意识
        smsLoginParam: {smsCode: 假装有点保密意识,deviceId: 719910247738029,mobile: username,version: 3.0.0,grant_type: sms_code}
        smsUri: /sms/code
        loginUri: /oauth/token
        tokenPath: $.access_token
        loginRely:
          token: $.access_token
        deviceTypeList:
          - 唐胖的三包账号
        environment:
          - loginHost: 假装有点保密意识
            loginHeader: {Authorization: Basic 假装有点保密意识}
            smsHeader: {}
            account:
              - - 12900000012
            host: 假装有点保密意识
          - loginHost: 假装有点保密意识
            loginHeader: {Authorization: Basic 假装有点保密意识}
            smsHeader: {}
            account:
              - - 12900000205
                - 12900000205
              - - 12900000205
            host: 假装有点保密意识
          - loginHost: 假装有点保密意识
            loginHeader: {Authorization: Basic 假装有点保密意识}
            smsHeader: {}
            account:
              - - 13588096710
                - 18657190534
              - - 1358809666
            host: 假装有点保密意识


      - device4:
        id: 4
        name: 知轮通
        loginPage: 假装有点保密意识
        loginType: 1
        smsParam: {}
        loginParam:
          grant_type: password
          username: username
          password: 假装有点保密意识
          application: 假装有点保密意识
          appVersionCode: 217
        smsLoginParam: {smsCode: 假装有点保密意识,deviceId: 719910247738029,mobile: username,version: 3.0.0,grant_type: sms_code}
        smsUri: /sms/code
        loginUri: /oauth/token
        tokenPath: $.access_token
        loginRely:
          token: $.access_token
          userId: $.userId
          scope: $.scope
        deviceTypeList:
          - 业务员-管理员账号
          - 业务员-员工
          - 业务员-主管
          - 合作公司-老板
          - 合作公司-财务
          - 合作公司-后勤
          - 合作公司-主管
          - 合作公司-经理-手下有人
          - 合作公司-经理-手下无人
        environment:
          - loginHost: 假装有点保密意识
            loginHeader: {Authorization: Basic 假装有点保密意识=}
            smsHeader: {}
            account:
              - - 13588096730
            host: 假装有点保密意识
          - loginHost: 假装有点保密意识
            loginHeader: {Authorization: Basic 假装有点保密意识}
            smsHeader: {}
            account:
              - - 12900000205
                - 12900000205
              - - 12900000205
            host: 假装有点保密意识
          - loginHost: 假装有点保密意识
            loginHeader: {Authorization: Basic 假装有点保密意识}
            smsHeader: {}
            account:
              - - 13588096710
                - 186571905346
              - - 1358809666
            host: 假装有点保密意识
      - device5:
        loginPage: c假装有点保密意识
        id: 5
        name: 分仓终端
        loginType: 1
        smsParam: {}
        loginParam:
          username: username
          password: 假装有点保密意识
          scanVersion: 20200303
          y: 35.250118
          x: 113.236565
          deviceNum: ZX1G42CPJD
        smsLoginParam: {smsCode: 假装有点保密意识,deviceId: 假装有点保密意识,mobile: username,version: 3.0.0,grant_type: sms_code}
        smsUri: sms/code
        loginUri: /scan/login.do
        tokenPath: $.access_token
        loginRely:
          token: $.access_token
          userId: $.userId
          scope: $.scope
        deviceTypeList:
          - test
        environment:
          - loginHost: 假装有点保密意识
            loginHeader: {Content-Type: application/x-www-form-urlencoded}
            smsHeader: {}
            account:
              - - test
            host: 假装有点保密意识
          - loginHost: 假装有点保密意识
            loginHeader: {}
            smsHeader: {}
            account:
              - - test
            host: 假装有点保密意识
          - loginHost: 假装有点保密意识
            loginHeader: {}
            smsHeader: {}
            account:
              - - test
            host: 假装有点保密意识
      - device6:
        id: 6
        name: 知轮车服
        loginPage: 假装有点保密意识
        loginType: 0
        smsParam:
          deviceId: 假装有点保密意识
          mobile: username
          application: app_driver
          appVersionCode: 138
        loginParam:
          grant_type: password
          username: username
          password: 假装有点保密意识
          application: app_message
          appVersionCode: 217
        smsLoginParam:
          grant_type: sms_code
          deviceId: 假装有点保密意识
          mobile: username
          smsCode: 假装有点保密意识
          application: app_driver
          appVersionCode: 138
        smsUri: /sms/code
        loginUri: /oauth/token
        tokenPath: $.access_token
        loginRely:
          token: $.access_token
          userId: $.userId
          scope: $.scope
        deviceTypeList:
          - 普通司机账号
          - 创建数据账号
        environment:
          - loginHost: 假装有点保密意识
            loginHeader: {Authorization: Basic 假装有点保密意识==}
            smsHeader: {}
            account:
              - - 12900000001
              - - 12900000448
            host: 假装有点保密意识
          - loginHost: 假装有点保密意识
            loginHeader: {Authorization: Basic 假装有点保密意识==}
            smsHeader: {}
            account:
              - - 12900000001
              - - 12900000448
            host: 假装有点保密意识
          - loginHost: 假装有点保密意识
            loginHeader: {Authorization: Basic 假装有点保密意识==}
            smsHeader: {}
            account:
              - - 12900000001
              - - 12900000448
            host: 假装有点保密意识
      - device7:
        id: 7
        name: 司机小程序
        loginPage: wechat
        loginType: 0
        smsParam:
          deviceId: wxCode
          mobile: username
        loginParam:
          grant_type: password
          username: username
          password: 假装有点保密意识
          application: app_message
          appVersionCode: 217
        smsLoginParam:
          mobile: username
          smsCode: 假装有点保密意识
          grant_type: wechat_mobile
          source: wechart
          code: wxCode
          inviter:
          channelName:
          application: app_driver_applets
        smsUri: 假装有点保密意识
        loginUri: 假装有点保密意识
        tokenPath: $.access_token
        loginRely:
          token: $.access_token
          userId: $.userId
          scope: $.scope
        deviceTypeList:
          - 普通司机账号
        environment:
          - loginHost: 假装有点保密意识
            loginHeader: {Authorization: Basic 假装有点保密意识==}
            smsHeader: {}
            account:
              - - 12900000001
            host: 假装有点保密意识


          - loginHost: 假装有点保密意识
            loginHeader: {Authorization: Basic 假装有点保密意识==}
            smsHeader: {}
            account:
              - - 12900000001
            host: 假装有点保密意识


          - loginHost: 假装有点保密意识
            loginHeader: {Authorization: Basic 假装有点保密意识==}
            smsHeader: {}
            account:
              - - 12900000001
            host: 假装有点保密意识
      - device8:
        id: 8
        name: 知轮商城
        loginPage: web
        loginType: 1
        smsParam:
          deviceId: wxCode
          mobile: username
        loginParam: {}
        smsLoginParam:
          mobile: username
          smsCode: 假装有点保密意识
          grant_type: wechat_mobile
          source: wechart
          code: wxCode
          inviter:
          channelName:
          application: app_driver_applets
        smsUri: 假装有点保密意识
        loginUri: 假装有点保密意识
        tokenPath: $.LOGINTOKEN
        loginRely:
          token: $.token
          LOGINTOKEN: $.LOGINTOKEN
          accId: $.accId
        deviceTypeList:
          - 普通司机账号
        environment:
          - loginHost: 假装有点保密意识
            loginHeader: {Authorization: Basic 假装有点保密意识==}
            smsHeader: {}
            account:
              - - 12900000001
            host: 假装有点保密意识


          - loginHost: 假装有点保密意识
            loginHeader: {Authorization: Basic 假装有点保密意识==}
            smsHeader: {}
            account:
              - - 12900000001
            host: 假装有点保密意识


          - loginHost: 假装有点保密意识
            loginHeader: {Authorization: Basic 假装有点保密意识==}
            smsHeader: {}
            account:
              - - 12900000001
            host: 假装有点保密意识
      - device9:
        id: 9
        name: 分仓后台
        loginPage: web
        loginType: 3
        smsParam: {}
        loginParam:
          username: username
          password: 假装有点保密意识
        smsLoginParam: {}
        smsUri: /index.do
        loginUri: /login.do
        tokenPath:
        loginRely: {}
        deviceTypeList:
          - test
        environment:
          - loginHost: 假装有点保密意识
            loginHeader: {}
            smsHeader: {}
            account:
              - - test
            host: 假装有点保密意识


          - loginHost: 假装有点保密意识
            loginHeader: {}
            smsHeader: {}
            account:
              - - test1
            host: 假装有点保密意识


          - loginHost: 假装有点保密意识
            loginHeader: {}
            smsHeader: {}
            account:
              - - test1
            host: 假装有点保密意识
user:
  ip:
    - 192.168.20.135
    - 127.0.0.1
    - 192.168.20.237
    - 192.168.40.35
    - 192.168.10.222
    - 192.168.10.70














