server:
  port: 8080
spring:
  thymeleaf:
    cache: false

  #\u914D\u7F6E\u6570\u636E\u5E93
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: db_user
    password: kybb123456
    url: jdbc:mysql://dev-mysql.zhilun-base.com:3306/test_tsc_c?useUnicode=true&characterEncoding=UTF8&useSSL=false
    #\u90AE\u7BB1\u914D\u7F6E
  mail:
    host: smtp.qq.com
    port: 587
    username: 2465668576@qq.com
    password: mgjlurmdqgfieaig
    from: 2465668576@qq.com
    properties:
      mail:
        debug: true
      stmp:
        auth: true
        ssl:
          enable: true

#\u914D\u7F6Esql\u6620\u5C04
mybatis:
  type-aliases-package: com.service
  mapper-locations:
  - mapper/*
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


myhost:
  store:
    uat: https://api.t.zhilunkeji.com
    test: http://api.zhilun-qa-major.com
    tests: http://api.zhilun-qa-minor.com
    prod: https://api.zhilunkeji.com
    basic: TU9CSUxFX1NFUlZJQ0VfQ0FSOjU4NjgzZmU4ZWU2MDRmN2I5MTlhYzM0YTFmMjVkOGUy
    basics: TU9CSUxFX1NFUlZJQ0VfQ0FSOjEzNDgwNWRiZWIyODZhZjk3NTRjNTM5ODIzZGJmMTI4
    account: [13200000005,2,3,4,5,6]
    accounts: [1,2,3,4,5,6]
    uatl: https://auth.t.zhilunkeji.com
    testl: http://auth.zhilun-qa-major.com

  pda:
    uat: http://wch.zhilun.com/1001
    test: http://wh.zhilun-qa-minor.com/1001
    tests: http://wh.zhilun-qa-major.com/1001
    name: tsc
    password: 123456
  tweb:
    uat: https://ra.t.zhilunkeji.com
    test: http://manager.zhilun-qa-major.com
    basic: TUFOQUdFTUVOVDo2NTRjMzRkMGFkZTc0N2VlYTBmZDgzZmI5N2JlNzI4MA==
    basics: TUFOQUdFTUVOVDpjZGU1ZDQ5OGRmNWNkMGJmMTdlY2ZiYmJkZGY5M2E0Nw==
    name: tsc
    password : e10adc3949ba59abbe56e057f20f883e
  pweb:
    uat: https://w-t.zhilunkeji.com
    test: http://wh.zhilun-qa-minor.com/1001
    tests: http://wh.zhilun-qa-major.com/1001
    name: test
    password: e10adc3949ba59abbe56e057f20f883e








