server:
  port: 8080
spring:
  thymeleaf:
    cache: false

  #\u914D\u7F6E\u6570\u636E\u5E93
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: tsc123tsc123
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=UTC
    #\u90AE\u7BB1\u914D\u7F6E
  mail:
    host: smtp.qq.com
    port: 587
    username: 2465668576@qq.com
    password: mgjlurmdqgfieaig
    from: 2465668576@qq.com
    properties:
      mail:
        debug: true
      stmp:
        auth: true
        ssl:
          enable: true

#\u914D\u7F6Esql\u6620\u5C04
mybatis:
  type-aliases-package: com.service
  mapper-locations:
    - mapper/*
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


myhost:
  store:
    uat: https://api.t.zhilunkeji.com
    test: http://api.zhilun-qa-major.com
    tests: http://api.zhilun-qa-minor.com
    prod: https://api.zhilunkeji.com
    basic: TU9CSUxFX1NFUlZJQ0VfQ0FSOjU4NjgzZmU4ZWU2MDRmN2I5MTlhYzM0YTFmMjVkOGUy
    basics: TU9CSUxFX1NFUlZJQ0VfQ0FSOjEzNDgwNWRiZWIyODZhZjk3NTRjNTM5ODIzZGJmMTI4
    account: [12900000200,2,3,4,5,6,13588096710]
    accounts: [12900000200,2,3,4,5,6,13588096710]
    uatl: https://auth.t.zhilunkeji.com
    testl: http://auth.zhilun-qa-major.com
    testsl: http://auth.zhilun-qa-minor.com
    deviceType: [1,2,3,4,5,6,7]
  pda:
    uat: http://wch.zhilun.com/1001
    test: http://wch.zhilun-qa-minor.com/1001
    tests: http://wch.zhilun-qa-major.com/1001
    name: tsc
    password: 123456
  tweb:
    uat: https://ra.t.zhilunkeji.com
    test: http://manager.zhilun-qa-major.com
    basic: TUFOQUdFTUVOVDo2NTRjMzRkMGFkZTc0N2VlYTBmZDgzZmI5N2JlNzI4MA==
    basics: TUFOQUdFTUVOVDpjZGU1ZDQ5OGRmNWNkMGJmMTdlY2ZiYmJkZGY5M2E0Nw==
    name: tsc
    password: e10adc3949ba59abbe56e057f20f883e
    tests: http://manager.zhilun-qa-minor.com
  pweb:
    uat: https://w-t.zhilunkeji.com
    test: http://wh.zhilun-qa-major.com/1001
    tests: http://wh.zhilun-qa-minor.com/1001
    name: test
    password: e10adc3949ba59abbe56e057f20f883e
  driverapp:
    uat: https://api.t.zhilunkeji.com
    test: http://api.zhilun-qa-major.com
    tests: http://api.zhilun-qa-minor.com
    account: [13200000001,2,3,4,5,6]
    accounts: [12900000000,2,3,4,5,6]
    uatl: 25d55ad283aa400af464c76d713c07ad
    testl: http://auth.zhilun-qa-major.com
    testsl: http://auth.zhilun-qa-minor.com
    basic: VFJVQ0tFUjo2NDVjOGE5MjllNmM0MTJjOWZlYmY5MGIyYWQwNzM3NA==
    basics: VFJVQ0tFUjpiOGE1ZDc5ZmRmZmM3NzY2YzY0NzM1Mjg4YmViMDY0Yg==
    deviceType: [1,2,3,4,5,6,7]
  driversapp:
    uat: https://api.t.zhilunkeji.com
    test: http://api.zhilun-qa-major.com
    tests: http://api.zhilun-qa-minor.com
    account: [13200000001,2,3,4,5,6]
    accounts: [12900000000,2,3,4,5,6]
    uatl: 25d55ad283aa400af464c76d713c07ad
    testl: http://auth.zhilun-qa-major.com
    testsl: http://auth.zhilun-qa-minor.com
    basic: RU5URVJQUklTRV9VU0VSOjlIR291Wk1UQ0VGNllMVzA0SVF0QWhkS3FreWJsejc1T05yMw==
    basics: VFJVQ0tFUjpiOGE1ZDc5ZmRmZmM3NzY2YzY0NzM1Mjg4YmViMDY0Yg==
project:
  project1:
    environment:
      - 准生产
      - 测试主
      - 测试次
    name: 知轮
    id: 1 
    device:
      - device1:
        id: 1
        name: 管理后台
        loginType: 1
        loginParam: {username: username,password: e10adc3949ba59abbe56e057f20f883e,grant_type: password}
        smsParam: {}
        smsUri:
        smsLoginParam: {}
        loginUri: /oauth/token
        tokenPath: $.access_token
        loginRely:
          userId: $.userId
          token: $.access_token
        deviceTypeList:
          - 唐胖的管理后台账号
        environment:
          - loginHost: https://ra-t.zhilunkeji.com
            loginHeader: {Authorization: Basic TUFOQUdFTUVOVDpjZGU1ZDQ5OGRmNWNkMGJmMTdlY2ZiYmJkZGY5M2E0Nw==}
            smsHeader: {}
            account:
              - - tsc
                - tscpear
              - - 1358809666
            host: https://ra-t.zhilunkeji.com

          - loginHost: http://manager.zhilun-qa-major.com
            loginHeader: {Authorization: Basic TUFOQUdFTUVOVDpjZGU1ZDQ5OGRmNWNkMGJmMTdlY2ZiYmJkZGY5M2E0Nw==}
            smsHeader: {}
            account:
              - - tsc
                - tsccs
              - - 1358809666
            host: http://manager.zhilun-qa-major.com


          - loginHost: http://manager.zhilun-qa-minor.com
            loginHeader: {Authorization: Basic TUFOQUdFTUVOVDpjZGU1ZDQ5OGRmNWNkMGJmMTdlY2ZiYmJkZGY5M2E0Nw== }
            smsHeader: {}
            account:
              - - tsc
                - tscpear
              - - 1358809666
            host: http://manager.zhilun-qa-minor.com



      - device2:
        id: 2
        name: 知轮商家
        loginType: 1
        smsParam: {deviceId: "719910247738029",mobile: "username"}
        loginParam:
          application: app_zhilun
          deviceId: 022f96f1cdaa4569810f601a0e830b06
          grant_type: store_password
          mobile: username
          password: e10adc3949ba59abbe56e057f20f883e
        smsLoginParam: {smsCode: cf79ae6addba60ad018347359bd144d2,deviceId: 719910247738029,mobile: username,version: 3.0.0,grant_type: sms_code}
        smsUri: /sms/code
        loginUri: /oauth/token
        tokenPath: $.access_token
        loginRely:
          token: $.access_token
          userId: $.userId
          userType: $.userType
          scope: $.scope
        deviceTypeList:
          - 网红门店账号
          - 网红门店下服务车账号
          - 普通门店账号
          - 普通社会服务车账号
          - 取货点
          - 取货方门店账号
          - 取货方门店下服务车账号
          - 取货方社会服务车账号
        environment:
#          准生产
          - loginHost: https://auth-t.zhilunkeji.com
            loginHeader: {Authorization: Basic TU9CSUxFX1NFUlZJQ0VfQ0FSOjEzNDgwNWRiZWIyODZhZjk3NTRjNTM5ODIzZGJmMTI4}
            smsHeader: {}
            account:
              - - 13588096710
                - 18329133828
              - - 12900000205
            host: https://api-t.zhilunkeji.com
#            测试主
          - loginHost: http://auth.zhilun-qa-major.com
            loginHeader: {Authorization: Basic TU9CSUxFX1NFUlZJQ0VfQ0FSOjEzNDgwNWRiZWIyODZhZjk3NTRjNTM5ODIzZGJmMTI4}
            smsHeader: {}
            account:
              - - 12900000205
                - 12900000205
              - - 12900000205
            host: http://api.zhilun-qa-major.com
#            测试次
          - loginHost: http://auth.zhilun-qa-minor.com
            loginHeader: {Authorization: Basic TU9CSUxFX1NFUlZJQ0VfQ0FSOjEzNDgwNWRiZWIyODZhZjk3NTRjNTM5ODIzZGJmMTI4}
            smsHeader: {}
            account:
              - - 13588096710
                - 186571905346
              - - 1358809666
            host: http://api.zhilun-qa-minor.com
      - device3:
        id: 3
        name: 知轮三包
        loginType: 1
        smsParam: {deviceId: "719910247738029",mobile: "username"}
        loginParam:
          grant_type: password
          username: username
          password: e10adc3949ba59abbe56e057f20f883e
        smsLoginParam: {smsCode: cf79ae6addba60ad018347359bd144d2,deviceId: 719910247738029,mobile: username,version: 3.0.0,grant_type: sms_code}
        smsUri: /sms/code
        loginUri: /oauth/token
        tokenPath: $.access_token
        loginRely:
          token: $.access_token
        deviceTypeList:
          - 唐胖的三包账号
        environment:
          - loginHost: https://auth-t.zhilunkeji.com
            loginHeader: {Authorization: Basic VEhSRUVHVUFSQU5URUU6b052bEphN1VuSUF5Slk5Z2hZWkFRcVR5aTZldTRP}
            smsHeader: {}
            account:
              - - 13588096710
            host: https://api-t.zhilunkeji.com
          - loginHost: http://auth.zhilun-qa-major.com
            loginHeader: {Authorization: Basic VEhSRUVHVUFSQU5URUU6b052bEphN1VuSUF5Slk5Z2hZWkFRcVR5aTZldTRP}
            smsHeader: {}
            account:
              - - 12900000205
                - 12900000205
              - - 12900000205
            host: http://api.zhilun-qa-major.com
          - loginHost: http://auth.zhilun-qa-minor.com
            loginHeader: {Authorization: Basic VEhSRUVHVUFSQU5URUU6b052bEphN1VuSUF5Slk5Z2hZWkFRcVR5aTZldTRP}
            smsHeader: {}
            account:
              - - 13588096710
                - 186571905346
              - - 1358809666
            host: http://api.zhilun-qa-minor.com


      - device4:
        id: 4
        name: 知轮通
        loginType: 1
        smsParam: {}
        loginParam:
          grant_type: password
          username: username
          password: e10adc3949ba59abbe56e057f20f883e
          application: app_message
          appVersionCode: 217
        smsLoginParam: {smsCode: cf79ae6addba60ad018347359bd144d2,deviceId: 719910247738029,mobile: username,version: 3.0.0,grant_type: sms_code}
        smsUri: /sms/code
        loginUri: /oauth/token
        tokenPath: $.access_token
        loginRely:
          token: $.access_token
          userId: $.userId
          scope: $.scope
        deviceTypeList:
          - 业务员-管理员账号
          - 业务员-员工
          - 业务员-主管
          - 合作公司-老板
          - 合作公司-财务
          - 合作公司-后勤
          - 合作公司-主管
          - 合作公司-经理-手下有人
          - 合作公司-经理-手下无人
        environment:
          - loginHost: https://auth-t.zhilunkeji.com
            loginHeader: {Authorization: Basic Q1VTVE9NRVJfU0VSVklDRTpvTnZsSmE3VW5JQXlKWTlnaFlaQVFxVHlpNmV1NE8=}
            smsHeader: {}
            account:
              - - 13588096730
            host: https://api-t.zhilunkeji.com
          - loginHost: http://auth.zhilun-qa-major.com
            loginHeader: {Authorization: Basic VEhSRUVHVUFSQU5URUU6b052bEphN1VuSUF5Slk5Z2hZWkFRcVR5aTZldTRP}
            smsHeader: {}
            account:
              - - 12900000205
                - 12900000205
              - - 12900000205
            host: http://api.zhilun-qa-major.com
          - loginHost: http://auth.zhilun-qa-minor.com
            loginHeader: {Authorization: Basic VEhSRUVHVUFSQU5URUU6b052bEphN1VuSUF5Slk5Z2hZWkFRcVR5aTZldTRP}
            smsHeader: {}
            account:
              - - 13588096710
                - 186571905346
              - - 1358809666
            host: http://api.zhilun-qa-minor.com
      - device5:
        id: 5
        name: 分仓终端
        loginType: 1
        smsParam: {}
        loginParam:
          username: username
          password: 123456
          scanVersion: 20200303
          y: 35.250118
          x: 113.236565
          deviceNum: ZX1G42CPJD
        smsLoginParam: {smsCode: cf79ae6addba60ad018347359bd144d2,deviceId: 719910247738029,mobile: username,version: 3.0.0,grant_type: sms_code}
        smsUri: sms/code
        loginUri: /scan/login.do
        tokenPath: $.access_token
        loginRely:
          token: $.access_token
          userId: $.userId
          scope: $.scope
        deviceTypeList:
          - test
        environment:
          - loginHost: http://wch.zhilun.com/1001
            loginHeader: {Content-Type: application/x-www-form-urlencoded}
            smsHeader: {}
            account:
              - - test
            host: http://wch.zhilun.com/1001
          - loginHost: http://wch.zhilun-qa-major.com/1001
            loginHeader: {}
            smsHeader: {}
            account:
              - - test
            host: http://wch.zhilun-qa-major.com
          - loginHost: http://wch.zhilun-qa-minor.com/1001
            loginHeader: {}
            smsHeader: {}
            account:
              - - test
            host: http://wch.zhilun-qa-minor.com
      - device6:
        id: 6
        name: 知轮车服
        loginType: 0
        smsParam:
          deviceId: b8d0ec531985fa7ab475e995deb45826
          mobile: username
          application: app_driver
          appVersionCode: 138
        loginParam:
          grant_type: password
          username: username
          password: e10adc3949ba59abbe56e057f20f883e
          application: app_message
          appVersionCode: 217
        smsLoginParam:
          grant_type: sms_code
          deviceId: b8d0ec531985fa7ab475e995deb45826
          mobile: username
          smsCode: cf79ae6addba60ad018347359bd144d2
          application: app_driver
          appVersionCode: 138
        smsUri: /sms/code
        loginUri: /oauth/token
        tokenPath: $.access_token
        loginRely:
          token: $.access_token
          userId: $.userId
          scope: $.scope
        deviceTypeList:
          - 普通司机账号
        environment:
          - loginHost: https://auth-t.zhilunkeji.com
            loginHeader: {Authorization: Basic VFJVQ0tFUjpiOGE1ZDc5ZmRmZmM3NzY2YzY0NzM1Mjg4YmViMDY0Yg==}
            smsHeader: {}
            account:
              - - 12900000001
            host: https://api-t.zhilunkeji.com
          - loginHost: http://auth.zhilun-qa-major.com
            loginHeader: {Authorization: Basic VFJVQ0tFUjpiOGE1ZDc5ZmRmZmM3NzY2YzY0NzM1Mjg4YmViMDY0Yg==}
            smsHeader: {}
            account:
              - - 12900000001
            host: http://api.zhilun-qa-major.com
          - loginHost: http://auth.zhilun-qa-minor.com
            loginHeader: {Authorization: Basic VFJVQ0tFUjpiOGE1ZDc5ZmRmZmM3NzY2YzY0NzM1Mjg4YmViMDY0Yg==}
            smsHeader: {}
            account:
              - - 12900000001
            host: http://api.zhilun-qa-minor.com
      - device7:
        id: 7
        name: 司机小程序
        loginType: 0
        smsParam:
          deviceId: wxCode
          mobile: username
        loginParam:
          grant_type: password
          username: username
          password: e10adc3949ba59abbe56e057f20f883e
          application: app_message
          appVersionCode: 217
        smsLoginParam:
          mobile: username
          smsCode: cf79ae6addba60ad018347359bd144d2
          grant_type: wechat_mobile
          source: wechart
          code: wxCode
          inviter:
          channelName:
          application: app_driver_applets
        smsUri: /sms/code/wechat
        loginUri: /oauth/token
        tokenPath: $.access_token
        loginRely:
          token: $.access_token
          userId: $.userId
          scope: $.scope
        deviceTypeList:
          - 普通司机账号
        environment:
          - loginHost: https://auth-t.zhilunkeji.com
            loginHeader: {Authorization: Basic VFJVQ0tFUjpiOGE1ZDc5ZmRmZmM3NzY2YzY0NzM1Mjg4YmViMDY0Yg==}
            smsHeader: {}
            account:
              - - 12900000001
            host: https://api-t.zhilunkeji.com


          - loginHost: http://auth.zhilun-qa-major.com
            loginHeader: {Authorization: Basic VFJVQ0tFUjpiOGE1ZDc5ZmRmZmM3NzY2YzY0NzM1Mjg4YmViMDY0Yg==}
            smsHeader: {}
            account:
              - - 12900000001
            host: http://api.zhilun-qa-major.com


          - loginHost: http://auth.zhilun-qa-minor.com
            loginHeader: {Authorization: Basic VFJVQ0tFUjpiOGE1ZDc5ZmRmZmM3NzY2YzY0NzM1Mjg4YmViMDY0Yg==}
            smsHeader: {}
            account:
              - - 12900000001
            host: http://api.zhilun-qa-minor.com
      - device8:
        id: 8
        name: 知轮商城
        loginType: 1
        smsParam:
          deviceId: wxCode
          mobile: username
        loginParam: {}
        smsLoginParam:
          mobile: username
          smsCode: cf79ae6addba60ad018347359bd144d2
          grant_type: wechat_mobile
          source: wechart
          code: wxCode
          inviter:
          channelName:
          application: app_driver_applets
        smsUri: /sms/code/wechat
        loginUri: /member/login/createZhilun
        tokenPath: $.LOGINTOKEN
        loginRely:
          token: $.token
          LOGINTOKEN: $.LOGINTOKEN
          accId: $.accId
        deviceTypeList:
          - 普通司机账号
        environment:
          - loginHost: https://auth-t.zhilunkeji.com
            loginHeader: {Authorization: Basic VFJVQ0tFUjpiOGE1ZDc5ZmRmZmM3NzY2YzY0NzM1Mjg4YmViMDY0Yg==}
            smsHeader: {}
            account:
              - - 12900000001
            host: https://api-t.zhilunkeji.com


          - loginHost: http://shop.zhilun-qa-major.com
            loginHeader: {Authorization: Basic VFJVQ0tFUjpiOGE1ZDc5ZmRmZmM3NzY2YzY0NzM1Mjg4YmViMDY0Yg==}
            smsHeader: {}
            account:
              - - 12900000001
            host: http://shop.zhilun-qa-major.com


          - loginHost: http://shop.zhilun-qa-minor.com
            loginHeader: {Authorization: Basic VFJVQ0tFUjpiOGE1ZDc5ZmRmZmM3NzY2YzY0NzM1Mjg4YmViMDY0Yg==}
            smsHeader: {}
            account:
              - - 12900000001
            host: http://shop.zhilun-qa-minor.com
      - device9:
        id: 9
        name: 分仓后台
        loginType: 3
        smsParam: {}
        loginParam:
          username: username
          password: e10adc3949ba59abbe56e057f20f883e
        smsLoginParam: {}
        smsUri: /index.do
        loginUri: /login.do
        tokenPath:
        loginRely: {}
        deviceTypeList:
          - test
        environment:
          - loginHost: https://w-t.zhilunkeji.com
            loginHeader: {}
            smsHeader: {}
            account:
              - - test
            host: https://w-t.zhilunkeji.com


          - loginHost: http://wh.zhilun-qa-major.com
            loginHeader: {}
            smsHeader: {}
            account:
              - - test
            host: http://wh.zhilun-qa-major.com


          - loginHost: http://wh.zhilun-qa-minor.com
            loginHeader: {}
            smsHeader: {}
            account:
              - - test
            host: http://wh.zhilun-qa-minor.com
user:
  ip:
    - 192.168.20.135
    - 127.0.0.1













